### ISSUE TITLE
3D base printing problem

### ISSUE THREAD

**Issue by bennybo** [sgcderek/dsgc-helix-scaffold#3]
Hello Derek, I exported the drawing on openscad as an STL and printed on my 3d printer but the base came out as shown in the picture attached. Is there a setting I am not aware of that needs to be tweaked? Thanks for such a wonderful piece of software.

Thanks,
Brian.
![DSC_0080](https://github.com/sgcderek/dsgc-helix-scaffold/assets/47410001/3e8cf5ce-c13f-4d28-89e9-ffdea9e4e8c9)

**Comment by sgcderek** [comment]
Honestly I have no idea how this could have happened. Would it be possible for you to share the parameters you used, the OpenSCAD version you have, and the slicer you're using? It looks like an issue with the slicer software to me

**Comment by bennybo** [comment]
I found it. Its a box lid from a previous project. I didn't clear the workspace from a previous project. My bad.

**Comment by sgcderek** [comment]
No worries, especially when working with OpenSCAD and how it handles 2D extrusions things can sometimes get confusing
